env:
  global:
  - CIBW_BEFORE_BUILD="yum install -y gcc && yum install -y glibc.i686 && pip install
    numpy cython && cd requirements && bash install_cmake.bash && bash clone.bash
    && bash build.bash"
  - CIBW_TEST_REQUIRES="nose2"
  - CIBW_TEST_COMMAND="cd {project}/test && nose2"
  - CIBW_SKIP="cp33-* cp34-*"
  - TWINE_USERNAME=mmatl
matrix:
  include:
  - dist: trusty
    sudo: required
    language: python
    python: '3.6'
    services:
    - docker
install:
- if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then brew install python3; fi
- pip3 install cibuildwheel==0.7.1
script:
- cibuildwheel --output-dir wheelhouse
- |
  if [[ $TRAVIS_TAG ]]; then
    python -m pip install twine
    python -m twine upload wheelhouse/*.whl
  fi
deploy:
  provider: pypi
  skip_existing: true
  user: mmatl
  on:
    tags: true
    branch: master
  password:
    secure: ZPKskVP8SkdEk3biP9Wq1C4kr66WBIm6aT5WidJtx2gR55iz+LJQDNHSAHxRdp3A0q1dSqVbqT9Ltc5Grs4Bv8o7po1fys6isg8UPQtlKP06UsBOgpKoILx4lw1e+5MDr86PBVTjF31cenhcl4PcpvbjecWe8qqhrS6miGLWhoIPoIKsxNOW/wgQym4viYuz5ErSfwY80wK5PTW8+fESZQTemjN+WPAWkJC6aHtdYPNzZCninBVKaC38+8jn6BtuQoA55aPH+QNbWx1pVVEE8VdaAVxNd6vKMbeRSDUEwtAiaYdJwJQzLn6P7SsW9+i560VIUDkH7AXAOvs4DJCLREUmZ6EucYmfO0fbAZQGQQjv61QptsN7TQmWiXN+6cxcWwwRF519uf7I2LGacBRIyagQ0XvzcMCJmZINiN7r+ep1mdTy8M9LP4WB9hxBcpj65QqQIpBTjPof89e3nmXgXSJyyOXYW/gkE8Y8CnLw/2JgbW4TLllv9kMMlViSvFmlDooITF+U+KGQWl+DEy3Ks8NJQnGZXNvERcv2M3Wm+bnOeikppSbfB8y0Ee6YSNCKSYFuvqZ24yjQYYop5fYfea5maWGT5brrnM2Iw2hGlPtAmQSw8DRMWIx2muRwPNnGJAeoh6CclSGm8o1fXVNkjeRWGCOhnwCXeu9pN3RlTak=
  distributions: sdist bdist_wheel
