[build-system]
requires = ["setuptools", "wheel", "numpy", "Cython"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
before-all = "bash requirements/clone.bash && bash requirements/build.bash"
before-build = "pip install numpy cython"
manylinux-x86_64-image = "manylinux_2_24"
test-requires = "pytest"
test-command = "pytest {package}/test"