[build-system]
requires = ["setuptools", "wheel", "numpy", "Cython"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
skip = "pp*"
before-build = "pip install numpy Cython"
manylinux-x86_64-image = "manylinux_2_24"

[tool.cibuildwheel.linux]
before-all = "bash build_dependencies/install_linux.sh"
archs = ["x86_64"]

[tool.cibuildwheel.macos]
before-all = "bash build_dependencies/install_macos.sh"
test-requires = "pytest"
test-command = "pytest {package}/test"

[tool.cibuildwheel.windows]
before-all = "powershell build_dependencies\\install_windows.ps1"
archs = ["AMD64"]
test-requires = "pytest"
test-command = "pytest {package}\\test"