name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{matrix.platform}}
    runs-on: ${{matrix.platform}}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.0.0
    - uses: actions/upload-artifact@v2
      with:
        path: ./wheelhouse/*.whl